#!/bin/bash
mkdir 0pct_refine
mkdir bgmaps
for i in $(ls experiments/scenarios/aha/softobs_0pct/*.scenario);
do
	   ./bin/opthpa -scenario $i -gui disable 
done
mv results* bgmaps/
mv bgmaps experiments/results/opthpa

mkdir csc2f
for i in $(ls experiments/scenarios/opthpa/*.scenario);
do
   ./bin/opthpa -scenario $i -gui disable 
done
mv results* csc2f/
mv csc2f experiments/results/opthpa

