#!/bin/bash
mkdir 0pct_cache
for i in $(ls experiments/scenarios/softobs_0pct/*.scenario);
do
   ./bin/sample -scenario $i -gui disable -quality high  -clustersize 10
   ./bin/sample -scenario $i -gui disable -quality low  -clustersize 10
done
for i in $(ls experiments/scenarios/softobs_0pct/*.scenario);
do
   ./bin/sample -scenario $i -gui disable -quality high  -clustersize 15
   ./bin/sample -scenario $i -gui disable -quality low  -clustersize 15
done
for i in $(ls experiments/scenarios/softobs_0pct/*.scenario);
do
   ./bin/sample -scenario $i -gui disable -quality high  -clustersize 20
   ./bin/sample -scenario $i -gui disable -quality low  -clustersize 20
done
mv results_* 0pct_cache

mkdir 5pct_cache
for i in $(ls experiments/scenarios/softobs_5pct/*.scenario);
do
   ./bin/sample -scenario $i -gui disable -quality high  -clustersize 10
   ./bin/sample -scenario $i -gui disable -quality low  -clustersize 10
done
for i in $(ls experiments/scenarios/softobs_5pct/*.scenario);
do
   ./bin/sample -scenario $i -gui disable -quality high  -clustersize 15
   ./bin/sample -scenario $i -gui disable -quality low  -clustersize 15
done
for i in $(ls experiments/scenarios/softobs_5pct/*.scenario);
do
   ./bin/sample -scenario $i -gui disable -quality high  -clustersize 20
   ./bin/sample -scenario $i -gui disable -quality low  -clustersize 20
done
mv results_* 5pct_cache

mkdir 10pct_cache
for i in $(ls experiments/scenarios/softobs_10pct/*.scenario);
do
   ./bin/sample -scenario $i -gui disable -quality high  -clustersize 10
   ./bin/sample -scenario $i -gui disable -quality low  -clustersize 10
done
for i in $(ls experiments/scenarios/softobs_10pct/*.scenario);
do
   ./bin/sample -scenario $i -gui disable -quality high  -clustersize 15
   ./bin/sample -scenario $i -gui disable -quality low  -clustersize 15
done
for i in $(ls experiments/scenarios/softobs_10pct/*.scenario);
do
   ./bin/sample -scenario $i -gui disable -quality high  -clustersize 20
   ./bin/sample -scenario $i -gui disable -quality low  -clustersize 20
done
mv results_* 10pct_cache
